export default {
    mainContainer: {marginLeft: 15, marginRight: 15},
    header: {flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center'},
    headerLabel: {fontFamily: "Poppins-Regular", fontSize: 24, marginTop: 30, color: 'white'},
    notificationIcon: {marginTop: 25, height: 25, width: 25},
    locationContainer: {marginTop: 30, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center'},
    locationDate: {fontFamily: "Poppins-Regular", fontSize: 18, color: 'white'},
    locationPlace: {fontFamily: "Poppins-Regular", fontSize: 14, color: "#CCCCCC"},
    locationMap: { borderRadius: 15, borderWidth: 5, borderColor: "grey"},
    locationMapBackground: {width: 64, height: 64, alignItems: 'center', justifyContent: 'center'},
    locationMapPointer: {height: 20, width: 17},
    searchInput: (width) => ({ paddingLeft: width/3, marginTop: 30, width: width*0.92, fontFamily: "Poppins-Regular", fontSize: 12,
    backgroundColor: '#323232', borderRadius: 12, color: 'white'}),
    todayEventLabel: {fontSize: 14, fontFamily: "Poppins-Regular", color: 'white', marginTop: 30},
    todayEventBg: (width) => ({width: width*0.92, height: 180, marginTop: 10}),
    todayEventContent: {flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 10, marginHorizontal: 15},
    todayEventName: {fontFamily: "Poppins-Medium", fontSize: 20, color: 'white'},
    todayEventDate: {backgroundColor: 'white', paddingHorizontal: 7, borderRadius: 10, alignItems: 'center',
    justifyContent: 'center', paddingVertical: 3},
    todayEventDay: {fontSize: 14, fontFamily: "Poppins-Bold", color: 'black'},
    todayEventMonth: {fontSize: 10, fontFamily: "Poppins-Medium", color: '#A1A1A1', marginTop: -5},
    todayEventFooter: {fontFamily: "Poppins-Light", fontSize: 14, color: 'white', position: 'absolute', bottom: 10, right: 20},
    scrollIndicatorContainer: {flexDirection: 'row', alignSelf: 'center', marginTop: 10},
    scrollIndicator: {width: 8, height: 8, borderRadius: 23, backgroundColor: 'white'},
    eventForYou: {flexDirection: 'row', justifyContent: 'space-between', marginTop: 30, alignItems: 'center'},
    eventForYouLabel: {fontFamily: "Poppins-Regular", fontSize: 14, color: 'white'},
    eventForYouLabel2: {fontFamily: "Poppins-Regular", fontSize: 12, color: 'white'},
    eventForYouBg: (width) => ({width: width/1.5, height: 150, marginTop: 10, marginRight: 15}),
    eventForYouContent: {backgroundColor: 'white', paddingHorizontal: 7, borderRadius: 10, alignItems: 'center',
    justifyContent: 'center', paddingVertical: 1, alignSelf: 'flex-end', marginTop: 10, marginRight: 10},
    eventForYouDay: {fontSize: 14, fontFamily: "Poppins-Bold", color: 'black'},
    eventForYouMonth: {fontSize: 10, fontFamily: "Poppins-Medium", color: '#A1A1A1', marginTop: -5},
    eventForYouName: {fontFamily: "Poppins-Medium", fontSize: 14, color: 'white', marginHorizontal: 15, marginTop: 40},
    eventForYouDetails: {flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 10, marginHorizontal: 15},
    eventForYouGenre: {fontFamily: "Poppins-Light", fontSize: 10, color: 'white'},
    eventForYouTime: {fontFamily: "Poppins-Light", fontSize: 10, color: 'white'},
    popularEvents: {flexDirection: 'row', alignItems: 'center', marginTop: 30, justifyContent: 'space-between'},
    popularEventsLabel: {fontFamily: "Poppins-Regular", fontSize: 14, color: 'white'},
    popularEventsLabel2: {fontFamily: "Poppins-Regular", fontSize: 12, color: 'white'},
    popularEventsContainer: {marginBottom: 70},
    popularEventsBg: (width) => ({width: width*.92, height: 280, marginTop: 10, marginBottom: 15}),
    popularEventsDate: {backgroundColor: 'white', paddingHorizontal: 12, borderRadius: 10, alignItems: 'center',
    justifyContent: 'center', paddingVertical: 2, alignSelf: 'flex-end', marginTop: 15, marginRight: 15},
    popularEventsDay: {fontSize: 20, fontFamily: "Poppins-Bold", color: 'black'},
    popularEventsMonth: {fontSize: 12, fontFamily: "Poppins-Medium", color: '#A1A1A1', marginTop: -5},
    popularEventsName: {fontFamily: "Poppins-Medium", fontSize: 20, color: 'white', marginHorizontal: 15, marginTop: 130},
    popularEventsDetails: {flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 10, marginHorizontal: 15},
    popularEventsGenre: {fontFamily: "Poppins-Light", fontSize: 12, color: 'white'},
    popularEventsTime: {fontFamily: "Poppins-Light", fontSize: 12, color: 'white'},
    bottomTab: (width) => ({position: 'absolute', bottom: 0, width: width, backgroundColor: 'black', opacity: 0.9, alignItems: 'center',
    justifyContent: 'space-around', flexDirection: 'row', paddingTop: 20, paddingBottom: 40}),
    tabIcons: {height: 20, width: 20},
    bottomBar: (width) => ({backgroundColor: 'white', height: 5, width: width/3, alignSelf: 'center', borderRadius: 23, marginBottom: 10}),
  }